### ISSUE TITLE
Rake breaks

### ISSUE THREAD

**Issue by Burgestrand** [Burgestrand/livereload-rails#12]
Trying to figure out the Rails server port, but there is no Rails server.

**Comment by Burgestrand** [comment]
/Users/dev/.rvm/gems/ruby-2.2.2/gems/railties-4.2.4/lib/rails/commands/server.rb:12:in `parse!': invalid option: --pattern (OptionParser::InvalidOption)
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:315:in `parse_options'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:190:in `options'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/livereload_rails-1.0.2/lib/livereload_rails/railtie.rb:8:in `<class:Railtie>'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/livereload_rails-1.0.2/lib/livereload_rails/railtie.rb:7:in `<module:LivereloadRails>'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/livereload_rails-1.0.2/lib/livereload_rails/railtie.rb:6:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/skylight-0.8.1/lib/skylight/probes.rb:81:in `require'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/skylight-0.8.1/lib/skylight/probes.rb:81:in `require'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/livereload_rails-1.0.2/lib/livereload_rails.rb:8:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
	from /Users/dev/Projects/battleriff/config/application.rb:16:in `<top (required)>'
	from /Users/dev/Projects/battleriff/config/environment.rb:2:in `require'
	from /Users/dev/Projects/battleriff/config/environment.rb:2:in `<top (required)>'
	from /Users/dev/Projects/battleriff/spec/rails_helper.rb:3:in `require'
	from /Users/dev/Projects/battleriff/spec/rails_helper.rb:3:in `<top (required)>'
	from /Users/dev/Projects/battleriff/spec/features/conversations_spec.rb:1:in `require'
	from /Users/dev/Projects/battleriff/spec/features/conversations_spec.rb:1:in `<top (required)>'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `load'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1327:in `block in load_spec_files'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `each'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/configuration.rb:1325:in `load_spec_files'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:102:in `setup'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:88:in `run'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:73:in `run'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/lib/rspec/core/runner.rb:41:in `invoke'
	from /Users/dev/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.3.2/exe/rspec:4:in `<main>'

**Comment by Burgestrand** [comment]
Unable to reproduce for now. I know I've seen it.
