### ISSUE TITLE
Asset logical path has no extension

### ISSUE THREAD

**Issue by leuchovius** [Burgestrand/livereload-rails#6]
Received this when using SCSS partial and `@import`:

```
/Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/asset.rb:36:in `initialize': Asset logical path has no extension: modules (Sprockets::ArgumentError)
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:380:in `new'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:380:in `build_asset'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:94:in `block in build_asset'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/caching.rb:58:in `cache_asset'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:93:in `build_asset'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/base.rb:287:in `find_asset'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/index.rb:61:in `find_asset'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/sprockets-2.12.3/lib/sprockets/environment.rb:75:in `find_asset'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/livereload-rails-1.0.0/lib/livereload-rails/middleware.rb:14:in `block (2 levels) in initialize'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/filewatcher-0.4.0/lib/filewatcher.rb:35:in `block in watch'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/filewatcher-0.4.0/lib/filewatcher.rb:29:in `loop'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/filewatcher-0.4.0/lib/filewatcher.rb:29:in `watch'
    from /Users/johannesleuchovius/.rvm/gems/ruby-2.2.0/gems/livereload-rails-1.0.0/lib/livereload-rails/watcher.rb:9:in `run'
```

**Comment by Burgestrand** [comment]
Fixed in f3ca3dae0112ce18db8edc457c0c0fc239dc798a.
